/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        result = new javax.swing.JLabel();
        ytxt = new javax.swing.JTextField();
        xtxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        opchooser = new javax.swing.JComboBox<>();
        res = new javax.swing.JLabel();
        mod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Resultado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        opchooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/", "X!", "Y^x", "e^x", "10^x", "sin x", "cos x" }));
        opchooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opchooserActionPerformed(evt);
            }
        });

        res.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mod.setText("Residuo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(xtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(opchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(mod)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(opchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String xS = xtxt.getText(), yS = ytxt.getText();

        if (xS.matches("[0-9]+") && yS.matches("[0-9]+")) {

            int x = Integer.parseInt(xS);
            int y = Integer.parseInt(yS);
            switch (opchooser.getSelectedIndex()) {
                case 0:
                    result.setText(String.valueOf(sum(x, y)));
                    break;
                case 1:
                    result.setText(String.valueOf(subs(x, y)));
                    break;
                case 2:
                    result.setText(String.valueOf(mult(x, y)));
                    break;
                case 3:
                    result.setText(String.valueOf(div(x, y)));
                    res.setText(String.valueOf(div2(x, y)));
                    break;
                case 5:
                    result.setText(String.valueOf(pot(x, y)));
                    break;
                case 8:
                    break;
                case 9:
                    break;
            }
        }

        int x = Integer.parseInt(xS);
        if (opchooser.getSelectedIndex() == 4) {
            result.setText(String.valueOf(fact(x)));
        } else if (opchooser.getSelectedIndex() == 6) {
            result.setText(String.valueOf(eu(x)));
        } else if (opchooser.getSelectedIndex() == 7) {
            result.setText(String.valueOf(pot2(x)));
        }

    }

    int subs(int x, int y) {
        int complement = 10, counter = 0, result;
        while (y > complement) {
            complement = mult(complement, 10);
        }
        for (int i = y; i < complement; i++) {
            counter++;
        }
        while (String.valueOf(x).length() > String.valueOf(counter).length()) {
            counter = Integer.parseInt("9" + counter);
        }

        result = Integer.parseInt(String.valueOf(sum(counter, x)).substring(1));
        return result;
    }

    int sum(int x, int y) {
        return x + y;
    }

    int mult(int x, int y) {
        int result = 0;
        for (int i = 0; i < y; i++) {
            result = sum(result, x);
        }
        return result;
    }

    int div(int x, int y) {
        int result, c = 1;

        result = subs(x, y);
        while (result >= y) {
            x = result;
            result = subs(x, y);

            c++;
        }

        return c;
    }

    int div2(int x, int y) {
        int result;

        result = subs(x, y);
        while (result >= y) {
            x = result;
            result = subs(x, y);
        }
        return result;
    }

    int fact(int x) {
        int result = x;

        for (int i = x; i >= 2; i--) {
            result = mult(result, (i - 1));
        }
        return result;
    }

    int pot(int x, int y) {
        int result = x;

        for (int i = 1; i < y; i++) {
            result = mult(result, x);
        }
        return result;
    }

    int pot2(int x) {
        int result = 10;

        for (int i = 1; i < x; i++) {
            result = mult(result, 10);
        }
        return result;
    }

    double eu(int x) {
        double result = 2.71;

        for (int i = 1; i < x; i++) {
            result = result * 2.71;
        }
        return result;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void opchooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opchooserActionPerformed
        int i = opchooser.getSelectedIndex();

        if (i == 3) {
            ytxt.setEnabled(true);
            mod.setEnabled(true);
        } else if (i == 5) {
            ytxt.setEnabled(true);
        } else if (i == 7) {
            ytxt.setEnabled(false);
        } else {
            ytxt.setEnabled(false);
            mod.setEnabled(false);
        }


    }//GEN-LAST:event_opchooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mod;
    private javax.swing.JComboBox<String> opchooser;
    private javax.swing.JLabel res;
    private javax.swing.JLabel result;
    private javax.swing.JTextField xtxt;
    private javax.swing.JTextField ytxt;
    // End of variables declaration//GEN-END:variables
}
